# Generated by Django 3.1.7 on 2021-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiсles',
            options={},
        ),
        migrations.AddField(
            model_name='artiсles',
            name='slug',
            field=models.SlugField(default='dfqqnfiiypsukvep', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
