# Generated by Django 3.1.7 on 2021-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210402_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiсles',
            name='slug',
            field=models.SlugField(default='oslmpzzrpcdmixeo', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
