# Generated by Django 3.1.7 on 2021-04-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=250)),
                ('document', models.FileField(upload_to='media/main')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
